### ISSUE TITLE
Problem: Profile settings page doesn't load if max profile fields isn't set

### ISSUE THREAD

**Issue by jorgesat** [magicstone-dev/ecko#373] opened 2022-01-04 07:48 UTC
The profile settings page on https://domain.tld/settings/profile is not loading after updating to the latest version on Yunohost.
I am running version 3.4.9001.

**Comment by weex** [comment] 2022-01-04 18:37
Confirmed. @jorgesat do you happen to have a relevant error in the ecko web service's logs?

**Comment by weex** [comment] 2022-01-04 20:33
```
Jan 04 20:32:37 bundle[2022]: [f62f8b33-ab8f-4024-b566-25b6ac39eeda] method=GET path=/settings/profile format=html controller=Settings::ProfilesController action=show status=500 error='ArgumentError: comparison of Integer with nil failed' duration=41.33 view=0.00 db=10.36
Jan 04 20:32:37 bundle[2022]: [f62f8b33-ab8f-4024-b566-25b6ac39eeda]
Jan 04 20:32:37 bundle[2022]: [f62f8b33-ab8f-4024-b566-25b6ac39eeda] ArgumentError (comparison of Integer with nil failed):
Jan 04 20:32:37 bundle[2022]: [f62f8b33-ab8f-4024-b566-25b6ac39eeda]
Jan 04 20:32:37 bundle[2022]: [f62f8b33-ab8f-4024-b566-25b6ac39eeda] app/models/account.rb:340:in `>='
Jan 04 20:32:37 bundle[2022]: [f62f8b33-ab8f-4024-b566-25b6ac39eeda] app/models/account.rb:340:in `build_fields'
Jan 04 20:32:37 bundle[2022]: [f62f8b33-ab8f-4024-b566-25b6ac39eeda] app/controllers/settings/profiles_controller.rb:7:in `show'
Jan 04 20:32:37 bundle[2022]: [f62f8b33-ab8f-4024-b566-25b6ac39eeda] app/controllers/concerns/localized.rb:16:in `block in set_locale'
Jan 04 20:32:37 bundle[2022]: [f62f8b33-ab8f-4024-b566-25b6ac39eeda] app/controllers/concerns/localized.rb:15:in `set_locale'
Jan 04 20:32:37 bundle[2022]: [9d04c4b2-4acb-491f-b263-dee39287e068] method=POST path=/api/v1/markers format=*/* controller=Api::V1::MarkersController action=create status=200 duration=45.86 view=0.60 db=30.16
```

**Comment by weex** [comment] 2022-01-04 20:37
Workaround: Go to https://ecko.magicstone.dev/settings/static_settings and set **Max profile metadata fields** to 4 (the default) or whatever other number of profile metadata fields you'd like your instance to have.

We've been working to make more things configurable through the UI and ran into an edge case here were a number was checked even though it wasn't yet set.

**Comment by jorgesat** [comment] 2022-01-05 07:57
Thanks. It is solved using the suggested workaround.

**Comment by jorgesat** [comment] 2022-01-05 08:10
I have to reopen the issue because the error persist once I try to save changes to a profile. The edit profile page opens normally but no changes can be applied.

**Comment by Mansh05** [comment] 2022-01-05 08:14
@jorgesat, Thanks for reopening again. Let me look at this and could you by chance help me with the workflow that you followed. Like what were the data that you typed and all and when refreshed then what happens. Meanwhile i will take what you have written above and check the bug.

**Comment by weex** [comment] 2022-01-05 08:16
Thanks for this. We do want leave this open until the root cause is solved. Bummer that it affects more than display. 

@Mansh05 any ideas for a proper fix?

**Comment by jorgesat** [comment] 2022-01-05 08:26
> @jorgesat, Thanks for reopening again. Let me look at this and could you by chance help me with the workflow that you followed. Like what were the data that you typed and all and when refreshed then what happens. Meanwhile i will take what you have written above and check the bug.

1. I changed the **Max profile metadata** fields to 4.
2. Profile settings page was working again.
3. I have opened a secondary profile I have (not admin) and made a change to the field "Bio", the change was not saved and an error message was displayed. If I try to change Display Name and Profile Metadata it works. The data is saved.

**Comment by jorgesat** [comment] 2022-01-05 08:33
Update: It works after setting all static settings. If have not set **Min profile description character** before.

**Comment by Mansh05** [comment] 2022-01-05 08:44
Ah great to hear, I will update fix for this where you don't need to set the settings and will take a default value.

**Comment by weex** [comment] 2022-01-14 21:52
Tested this with blanked out "Max profile metadata fields" and "Min profile description character" after the fix and it seems root cause is solved on `main`.

**Closed** 2022-01-17 21:59 UTC
