### ISSUE TITLE
Problem: A couple more themes

### ISSUE THREAD

**Issue by jorgesat** [magicstone-dev/ecko#338] opened 2021-12-20 08:42 UTC
Please, I would like to request a **feature**:
Include a couple more javascript theme styles. 

*Proposed solution:*
Please include the following themes in the 'app/javascript/styles' directory:
https://github.com/nibo-e/red-niboe/tree/main/site-settings/styles

**Comment by weex** [comment] 2021-12-20 19:35
Hey @jorgesat, thanks for creating this. I suppose the problem is "Not enough themes!" and I agree this is a valid and accurate problem.

Unless someone appears with valid objections, a PR that adds those and other themes to Ecko and doesn't fail testing would be merged.

**Comment by jorgesat** [comment] 2021-12-21 18:39
Thanks! Other popular themes are macaron and fairy-floss from hometown:

**Comment by weex** [comment] 2021-12-22 20:21
https://github.com/hometown-fork/hometown/commit/926d05eb590d3de6703ae304810f5a89739f6df6 looks like a decent template for how to add a theme.

Roughly speaking the steps are:
1. Add main scss file to config/themes.yml
2. Add nice name of theme for dropdown to config/locales/en.yml
3. Create a primary scss file that pulls in variables, application, and diff files.
4. Add variables and diff files to a folder just for the theme like app/javascript/styles/new-theme-name/

**Comment by weex** [comment] 2021-12-22 20:34
Hey @jorgesat Do you have nice names for the themes in that red-niboe repo you linked? Pulling those and the hometown ones into Ecko and wondering how they should be called.

**Comment by jorgesat** [comment] 2021-12-24 13:05
> Hey @jorgesat Do you have nice names for the themes in that red-niboe repo you linked? Pulling those and the hometown ones into Ecko and wondering how they should be called.

Hi, the names of the theme are the same as the filenames: merveilles-dark, niboe-oscuro and witches-colors.

**Comment by weex** [comment] 2021-12-27 19:15
@jorgesat These were merged and now we're preparing to bump the YunoHost release. So hopefully in a few days those themes will be available to everyone!

By our dev process, you who created the issue are the best one to close it once you've confirmed the issue is addressed.

**Closed** 2021-12-28 18:23 UTC
