### ISSUE TITLE
Problem: Unclear how to use Stripe plugin

### ISSUE THREAD

**Issue by weex** [magicstone-dev/ecko#311] opened 2021-12-09 17:29 UTC
Stripe plugin is in the codebase but it's not clear how to set it up so that admins can connect a stripe account and to pay for anything.

**Comment by Mansh05** [comment] 2021-12-10 16:57
1. One option to use stripe is to use it for boost option where people can come in and want their toot boosted. If they pay a certain amount then they can boost.
2. We can add a platform where people can come in help donate as well for the cause of ecko or any other needs posted by a user, moderated by the admin.

**Comment by weex** [comment] 2021-12-10 17:09
The initial use case I'm thinking of is as a donation with a badge like below but saying "Supporter" in green or gold that donors can optionally display on their profiles. Waiting on Stripe to ok my account for this kind of purpose before we do anything further on this particular use case.

<img width="200" alt="Screen Shot 2021-12-10 at 9 06 37 AM" src="https://user-images.githubusercontent.com/38776/145613435-892d400c-7828-4a5f-9f74-edc9bd730e6d.png">

Another might be to sell some merch like t-shirts, hats, stickers through a simple embedded store.

**Comment by Mansh05** [comment] 2021-12-10 17:33
Ah supporter tag would be nice actually. We could start off with that easily and with merch, it will be interesting.

**Closed** 2021-12-27 18:08 UTC
