### ISSUE TITLE
Problem: Not all config file edits take effect in YunoHost Ecko

### ISSUE THREAD

**Issue by ghost** [magicstone-dev/ecko#278] opened 2021-11-21 16:01 UTC
### Expected behaviour

I edited the .env.production file to increase the post character limit, the maximum number of poll options, the number of user fields in the profile and the character limit of the profile description

### Actual behaviour

only the post character limit changed. I still only have 4 poll options, 4 user fields and a small character limit for the profile description

### Steps to reproduce the problem

1. sudo su
2. vim /var/www/ecko/live/.env.production
3. edit the file to your liking
4. :wq!
5. restart the Ecko services in the YH admin panel
...

### Specifications

I'm running Ecko v3.4.9001 installed via YunoHost.

**Comment by weex** [comment] 2021-11-21 16:55
Confirmed that POLL_OPTIONS seems to be ignored and set at 4 even though the default installation on YunoHost is currently 5.

**Comment by weex** [comment] 2021-12-15 18:16
Version 2021.12.09\~ynh1 has been created for YunoHost and I got around to testing the upgrade. Since we changed version numbering to something more sane 2021-11-26\~ynh1 won't automatically update through the web interface. Instead you have to run `yunohost app upgrade -F ecko` (forcing it to update).

So @PaulaToThePeople if you want to do that upgrade, then you can see that these config files edits take effect after restart of services and if that's satisfactory, then you can close this.

Static settings should take immediate effect due to https://github.com/magicstone-dev/ecko/issues/315 with the next YunoHost release!

**Comment by PaulaToThePeople** [comment] 2021-12-15 22:04
Poll options changes now work, but configs on "about me" lenght and profile fields still don't take effect.

**Comment by weex** [comment] 2022-12-19 19:18
Closing this per C4-2.4.19 "Maintainers SHOULD close user issues that are left open without action for an uncomfortable period of time."

**Closed by weex** 2022-12-19 19:18 UTC
